fix curl installer

diff --git a/install-rockhopper b/install-rockhopper
--- a/install-rockhopper
+++ b/install-rockhopper
@@ -6,9 +6,57 @@ GH_FORK='mcandre'
 APP='rockhopper'
 DEST="$HOME/.local/bin"
 
-mkdir -p "$DEST"
-cd "$DEST"
+fallback() {
+    echo "select another install method: https://github.com/$GH_FORK/$APP/blob/main/INSTALL.md" >&2
+}
 
-curl -LO "https://raw.githubusercontent.com/$GH_FORK/$APP/refs/heads/main/bin/rockhopper"
-chmod +x "$APP"
+uname_to_rust_os() {
+    case "$1" in
+        Darwin*)
+            echo 'apple-darwin'
+            ;;
+        FreeBSD*)
+            echo 'unknown-freebsd'
+            ;;
+        Linux*)
+            echo 'unknown-linux-musl'
+            ;;
+        NetBSD*)
+            echo 'unknown-netbsd'
+            ;;
+        *illumos*)
+            echo 'unknown-illumos'
+            ;;
+        *)
+            echo "error: unsupported os. uname -a: $1" >&2
+            fallback
+            exit 1
+            ;;
+    esac
+}
+
+uname_arch_to_rust_arch() {
+    case "$1" in
+        aarch64 | arm64)
+            echo 'aarch64'
+            ;;
+        x86_64)
+            echo 'x86_64'
+            ;;
+        *)
+            echo "error: unsupported arch. uname -a: $(uname -a)" >&2
+            fallback
+            exit 1
+            ;;
+    esac
+}
+
+UNAME="$(uname -a)"
+OS="$(uname_to_rust_os "$UNAME")"
+ARCH="$(uname_arch_to_rust_arch "$(uname -m)")"
+TARBALL="$APP-$ARCH-$OS.tgz"
+curl -LO "https://github.com/$GH_FORK/$APP/releases/latest/download/$TARBALL"
+mkdir -p "$DEST"
+tar -C "$DEST" -xzf "$TARBALL"
+rm -rf "$TARBALL"
 echo "installed $APP binaries to $DEST"
