drop dead code; clarify macos os architectures; close #78

diff --git a/docker/alpine-linux/rocklet b/docker/alpine-linux/rocklet
--- a/docker/alpine-linux/rocklet
+++ b/docker/alpine-linux/rocklet
@@ -90,7 +90,7 @@ validate() {
         eval "required_env_val=\$$required_env_var"
 
         if [ -z "$required_env_val" ]; then
-            echo "error: ${rocklet_image}: blank/missing env var: ${required_env_var}"
+            echo "error: ${rocklet_image}: blank/missing env var: ${required_env_var}" >&2
             exit 1
         fi
     done
@@ -113,7 +113,7 @@ COPYING="$src/usr/share/licenses/$rocklet_name/COPYING"
 rsubst --strict "$rocklet_templates/COPYING.j2" >"$COPYING"
 
 if [ "$rocklet_log_level" = 'debug' ]; then
-    echo "COPYING:"
+    echo 'COPYING:'
     cat "$COPYING"
 fi
 
@@ -135,7 +135,7 @@ for f in $(find . -print); do
     elif [ -f "$f" ]; then
         apk_package="${apk_package}cp \"\$srcdir/$f\" \"\$pkgdir/$f\""
     else
-        echo "error: ${rocklet_image}: unsupported file system file type for path: ${source_media}/${f}"
+        echo "error: ${rocklet_image}: unsupported file system file type for path: ${source_media}/${f}" >&2
         exit 1
     fi
 done
@@ -147,7 +147,7 @@ APKBUILD="$rocklet_apk_build/$rocklet_name/APKBUILD"
 rsubst --strict "$rocklet_templates/APKBUILD.j2" >"$APKBUILD"
 
 if [ "$rocklet_log_level" = 'debug' ]; then
-    echo "APKBUILD:"
+    echo 'APKBUILD:'
     cat "$APKBUILD"
 fi
 
diff --git a/docker/fedora/rocklet b/docker/fedora/rocklet
--- a/docker/fedora/rocklet
+++ b/docker/fedora/rocklet
@@ -87,7 +87,7 @@ validate() {
         eval "required_env_val=\$$required_env_var"
 
         if [ -z "$required_env_val" ]; then
-            echo "error: ${rocklet_image}: blank/missing env var: ${required_env_var}"
+            echo "error: ${rocklet_image}: blank/missing env var: ${required_env_var}" >&2
             exit 1
         fi
     done
@@ -110,7 +110,7 @@ if [ -n "$rocklet_copyright" ]; then
     rsubst --strict "$rocklet_templates/COPYING.j2" >"$COPYING"
 
     if [ "$rocklet_log_level" = 'debug' ]; then
-        echo "COPYING:"
+        echo 'COPYING:'
         cat "$COPYING"
     fi
 fi
@@ -152,7 +152,7 @@ for f in $(find . -print); do
     elif [ -f "$f" ]; then
         fedora_data="${fedora_data}cp \"$source_media/$f\" \"%{buildroot}/$f\"; "
     else
-        echo "error: ${rocklet_image}: unsupported file system file type for path: ${source_media}/${f}"
+        echo "error: ${rocklet_image}: unsupported file system file type for path: ${source_media}/${f}" >&2
         exit 1
     fi
 done
@@ -175,7 +175,7 @@ SPEC="$rocklet_rpm_build/SPECS/$rocklet_name.spec"
 rsubst --strict "$rocklet_templates/.spec.j2" >"$SPEC"
 
 if [ "$rocklet_log_level" = 'debug' ]; then
-    echo "SPEC:"
+    echo 'SPEC:'
     cat "$SPEC"
 fi
 
diff --git a/docker/macos/rocklet b/docker/macos/rocklet
--- a/docker/macos/rocklet
+++ b/docker/macos/rocklet
@@ -16,7 +16,6 @@ rocklet_cache="${rocklet_cache:-"$rocklet_mount_path/.rockhopper"}"
 rocklet_artifact="${rocklet_artifact:-"$rocklet_cache/artifacts/macos"}"
 rocklet_pkg_build="${rocklet_pkg_build:-/tmp/macos}"
 rocklet_os_arch="${rocklet_os_arch:-"$(mename)"}"
-rocklet_dependencies="${rocklet_dependencies:-}"
 rocklet_uid="${rocklet_uid:-0}"
 rocklet_gid="${rocklet_gid:-0}"
 
@@ -92,7 +91,7 @@ validate() {
         eval "required_env_val=\$$required_env_var"
 
         if [ -z "$required_env_val" ]; then
-            echo "error: ${rocklet_image} blank/missing env var: ${required_env_var}"
+            echo "error: ${rocklet_image} blank/missing env var: ${required_env_var}" >&2
             exit 1
         fi
     done
@@ -124,7 +123,7 @@ if [ -n "$rocklet_copyright" ] || [ -n "$rocklet_license" ]; then
     rsubst --strict "$rocklet_templates/license.html.j2" >"$LICENSE_HTML"
 
     if [ "$rocklet_log_level" = 'debug' ]; then
-        echo "license.html:"
+        echo 'license.html:'
         cat "$LICENSE_HTML"
     fi
 fi
@@ -133,7 +132,7 @@ PACKAGEINFO="$BASE_PKG/PackageInfo"
 rsubst --strict "$rocklet_templates/PackageInfo.j2" >"$PACKAGEINFO"
 
 if [ "$rocklet_log_level" = 'debug' ]; then
-    echo "PackageInfo:"
+    echo 'PackageInfo:'
     cat "$PACKAGEINFO"
 fi
 
@@ -150,7 +149,7 @@ DISTRIBUTION="$rocklet_pkg_build/Distribution"
 rsubst --strict "$rocklet_templates/Distribution.j2" >"$DISTRIBUTION"
 
 if [ "$rocklet_log_level" = 'debug' ]; then
-    echo "Distribution:"
+    echo 'Distribution:'
     cat "$DISTRIBUTION"
 fi
 
