move data to unique rockhopper-data path; relates to #1; organize validation code

diff --git a/docker/alpine/rockhopper b/docker/alpine/rockhopper
--- a/docker/alpine/rockhopper
+++ b/docker/alpine/rockhopper
@@ -20,6 +20,7 @@ usage() {
     printf -- "--help\t\t\t\tShow usage menu.\n"
 }
 
+ROCKHOPPER_DATA_DIR='rockhopper-data'
 ARTIFACT_DIR='.rockhopper/alpine'
 
 clean() {
@@ -97,53 +98,57 @@ while [ "$#" -ge 1 ]; do
     esac
 done
 
-if [ "${NAME:-}" = '' ]; then
-    echo "error: blank/missing --name <name>"
-    usage
-    exit 1
-fi
+validate() {
+    if [ "${NAME:-}" = '' ]; then
+        echo "error: blank/missing --name <name>"
+        usage
+        exit 1
+    fi
 
-if [ "${VERSION:-}" = '' ]; then
-    echo "error: blank/missing --version <version>"
-    usage
-    exit 1
-fi
+    if [ "${VERSION:-}" = '' ]; then
+        echo "error: blank/missing --version <version>"
+        usage
+        exit 1
+    fi
 
-if [ "${RELEASE:-}" = '' ]; then
-    echo "error: blank/missing --release <release>"
-    usage
-    exit 1
-fi
+    if [ "${RELEASE:-}" = '' ]; then
+        echo "error: blank/missing --release <release>"
+        usage
+        exit 1
+    fi
 
-if [ "${ARCH:-}" = '' ]; then
-    echo "error: blank/missing --arch <architecture>"
-    usage
-    exit 1
-fi
+    if [ "${ARCH:-}" = '' ]; then
+        echo "error: blank/missing --arch <architecture>"
+        usage
+        exit 1
+    fi
 
-if [ "${MAINTAINER:-}" = '' ]; then
-    echo "error: blank/missing --maintainer <maintainer>"
-    usage
-    exit 1
-fi
+    if [ "${MAINTAINER:-}" = '' ]; then
+        echo "error: blank/missing --maintainer <maintainer>"
+        usage
+        exit 1
+    fi
 
-if [ "${DESCRIPTION:-}" = '' ]; then
-    echo "error: blank/missing --description <description>"
-    usage
-    exit 1
-fi
+    if [ "${DESCRIPTION:-}" = '' ]; then
+        echo "error: blank/missing --description <description>"
+        usage
+        exit 1
+    fi
 
-if [ "${LICENSE:-}" = '' ]; then
-    echo "error: blank/missing --license <license>"
-    usage
-    exit 1
-fi
+    if [ "${LICENSE:-}" = '' ]; then
+        echo "error: blank/missing --license <license>"
+        usage
+        exit 1
+    fi
 
-if [ "${URL:-}" = '' ]; then
-    echo "error: blank/missing --url <homepage>"
-    usage
-    exit 1
-fi
+    if [ "${URL:-}" = '' ]; then
+        echo "error: blank/missing --url <homepage>"
+        usage
+        exit 1
+    fi
+}
+
+validate
 
 cd /src
 
@@ -181,7 +186,7 @@ options=\"!check\"
 
 prepare() {
     default_prepare
-    cp -r /src/data/* \"\$builddir\"
+    cp -r /src/$ROCKHOPPER_DATA_DIR/* \"\$builddir\"
     mkdir -p \"\$builddir/usr/share/licenses/$NAME\"
     cp /tmp/LICENSE \"\$builddir/usr/share/licenses/$NAME\"
 }
@@ -191,7 +196,7 @@ package() {
     cp \"\$srcdir/usr/share/licenses/$NAME/LICENSE\" \"\$pkgdir/usr/share/licenses/$NAME/LICENSE\"
 "
 
-cd data
+cd "$ROCKHOPPER_DATA_DIR"
 for f in $(find . -print); do
     f="${f#./}"
 
@@ -204,7 +209,7 @@ for f in $(find . -print); do
     elif [ -f "$f" ]; then
         APKBUILD="$APKBUILD\n    cp \"\$srcdir/$f\" \"\$pkgdir/$f\""
     else
-        echo "error: unsupported file system file type for path: data/$f"
+        echo "error: unsupported file system file type for path: $ROCKHOPPER_DATA_DIR/$f"
         exit 1
     fi
 done
diff --git a/docker/arch/rockhopper b/docker/arch/rockhopper
--- a/docker/arch/rockhopper
+++ b/docker/arch/rockhopper
@@ -20,6 +20,7 @@ usage() {
     printf -- "--help\t\t\t\tShow usage menu.\n"
 }
 
+ROCKHOPPER_DATA_DIR='rockhopper-data'
 INTERNAL_DIR='archlinux'
 ARTIFACT_DIR='.rockhopper/arch'
 
@@ -98,53 +99,57 @@ while [ "$#" -ge 1 ]; do
     esac
 done
 
-if [ "${NAME:-}" = '' ]; then
-    echo "error: blank/missing --name <name>"
-    usage
-    exit 1
-fi
+validate() {
+    if [ "${NAME:-}" = '' ]; then
+        echo "error: blank/missing --name <name>"
+        usage
+        exit 1
+    fi
 
-if [ "${VERSION:-}" = '' ]; then
-    echo "error: blank/missing --version <version>"
-    usage
-    exit 1
-fi
+    if [ "${VERSION:-}" = '' ]; then
+        echo "error: blank/missing --version <version>"
+        usage
+        exit 1
+    fi
 
-if [ "${RELEASE:-}" = '' ]; then
-    echo "error: blank/missing --release <release>"
-    usage
-    exit 1
-fi
+    if [ "${RELEASE:-}" = '' ]; then
+        echo "error: blank/missing --release <release>"
+        usage
+        exit 1
+    fi
 
-if [ "${ARCH:-}" = '' ]; then
-    echo "error: blank/missing --arch <architecture>"
-    usage
-    exit 1
-fi
+    if [ "${ARCH:-}" = '' ]; then
+        echo "error: blank/missing --arch <architecture>"
+        usage
+        exit 1
+    fi
 
-if [ "${MAINTAINER:-}" = '' ]; then
-    echo "error: blank/missing --maintainer <maintainer>"
-    usage
-    exit 1
-fi
+    if [ "${MAINTAINER:-}" = '' ]; then
+        echo "error: blank/missing --maintainer <maintainer>"
+        usage
+        exit 1
+    fi
 
-if [ "${DESCRIPTION:-}" = '' ]; then
-    echo "error: blank/missing --description <description>"
-    usage
-    exit 1
-fi
+    if [ "${DESCRIPTION:-}" = '' ]; then
+        echo "error: blank/missing --description <description>"
+        usage
+        exit 1
+    fi
 
-if [ "${LICENSE:-}" = '' ]; then
-    echo "error: blank/missing --license <license>"
-    usage
-    exit 1
-fi
+    if [ "${LICENSE:-}" = '' ]; then
+        echo "error: blank/missing --license <license>"
+        usage
+        exit 1
+    fi
 
-if [ "${URL:-}" = '' ]; then
-    echo "error: blank/missing --url <homepage>"
-    usage
-    exit 1
-fi
+    if [ "${URL:-}" = '' ]; then
+        echo "error: blank/missing --url <homepage>"
+        usage
+        exit 1
+    fi
+}
+
+validate
 
 cd /src
 
@@ -161,7 +166,7 @@ license=('$LICENSE')
 depends=(${DEPENDENCIES:-})
 source=("
 
-cd data
+cd "$ROCKHOPPER_DATA_DIR"
 for f in $(find -type f -print); do
     f="${f#./}"
     b="$(basename "$f")"
@@ -179,7 +184,7 @@ package() {
     install \"\${srcdir}/LICENSE\" \"\${pkgdir}/usr/share/licenses/$NAME/LICENSE\"
 "
 
-cd data
+cd "$ROCKHOPPER_DATA_DIR"
 for f in $(find . -print); do
     f="${f#./}"
 
@@ -214,7 +219,7 @@ $LICENSE"
 mkdir -p "$INTERNAL_DIR/src"
 printf "$LIC\n" >"$INTERNAL_DIR/src/LICENSE"
 
-find data -type f -exec cp "{}" "$INTERNAL_DIR" \;
+find "$ROCKHOPPER_DATA_DIR" -type f -exec cp "{}" "$INTERNAL_DIR" \;
 
 cd "$INTERNAL_DIR"
 
diff --git a/docker/debian/rockhopper b/docker/debian/rockhopper
--- a/docker/debian/rockhopper
+++ b/docker/debian/rockhopper
@@ -20,6 +20,7 @@ usage() {
     printf -- "--help\t\t\t\tShow usage menu.\n"
 }
 
+ROCKHOPPER_DATA_DIR='rockhopper-data'
 INTERNAL_DIR='debian'
 ARTIFACT_DIR='.rockhopper/debian'
 
@@ -98,47 +99,51 @@ while [ "$#" -ge 1 ]; do
     esac
 done
 
-if [ "${NAME:-}" = '' ]; then
-    echo "error: blank/missing --name <name>"
-    usage
-    exit 1
-fi
+validate() {
+    if [ "${NAME:-}" = '' ]; then
+        echo "error: blank/missing --name <name>"
+        usage
+        exit 1
+    fi
 
-if [ "${VERSION:-}" = '' ]; then
-    echo "error: blank/missing --version <version>"
-    usage
-    exit 1
-fi
+    if [ "${VERSION:-}" = '' ]; then
+        echo "error: blank/missing --version <version>"
+        usage
+        exit 1
+    fi
 
-if [ "${RELEASE:-}" = '' ]; then
-    echo "error: blank/missing --release <release>"
-    usage
-    exit 1
-fi
+    if [ "${RELEASE:-}" = '' ]; then
+        echo "error: blank/missing --release <release>"
+        usage
+        exit 1
+    fi
 
-if [ "${ARCH:-}" = '' ]; then
-    echo "error: blank/missing --arch <architecture>"
-    usage
-    exit 1
-fi
+    if [ "${ARCH:-}" = '' ]; then
+        echo "error: blank/missing --arch <architecture>"
+        usage
+        exit 1
+    fi
 
-if [ "${MAINTAINER:-}" = '' ]; then
-    echo "error: blank/missing --maintainer <maintainer>"
-    usage
-    exit 1
-fi
+    if [ "${MAINTAINER:-}" = '' ]; then
+        echo "error: blank/missing --maintainer <maintainer>"
+        usage
+        exit 1
+    fi
 
-if [ "${DESCRIPTION:-}" = '' ]; then
-    echo "error: blank/missing --description <description>"
-    usage
-    exit 1
-fi
+    if [ "${DESCRIPTION:-}" = '' ]; then
+        echo "error: blank/missing --description <description>"
+        usage
+        exit 1
+    fi
 
-if [ "${LICENSE:-}" = '' ]; then
-    echo "error: blank/missing --license <license>"
-    usage
-    exit 1
-fi
+    if [ "${LICENSE:-}" = '' ]; then
+        echo "error: blank/missing --license <license>"
+        usage
+        exit 1
+    fi
+}
+
+validate
 
 cd /src
 
@@ -177,7 +182,7 @@ LIC="$LIC
 License: $LICENSE"
 printf "$LIC\n" >"$INTERNAL_DIR/DEBIAN/copyright"
 
-cp -r data/* "$INTERNAL_DIR"
+cp -r "$ROCKHOPPER_DATA_DIR/"* "$INTERNAL_DIR"
 
 mkdir -p "$ARTIFACT_DIR"
 ARTIFACT="$ARTIFACT_DIR/${NAME}_${VERSION}-${RELEASE}_${ARCH}.deb"
diff --git a/docker/rhel/rockhopper b/docker/rhel/rockhopper
--- a/docker/rhel/rockhopper
+++ b/docker/rhel/rockhopper
@@ -20,6 +20,7 @@ usage() {
     printf -- "--help\t\t\t\tShow usage menu.\n"
 }
 
+ROCKHOPPER_DATA_DIR='rockhopper-data'
 INTERNAL_DIR='/root/rpmbuild'
 ARTIFACT_DIR='/src/.rockhopper/rhel'
 
@@ -97,59 +98,63 @@ while [ "$#" -ge 1 ]; do
     esac
 done
 
-if [ "${NAME:-}" = '' ]; then
-    echo "error: blank/missing --name <name>"
-    usage
-    exit 1
-fi
+validate() {
+    if [ "${NAME:-}" = '' ]; then
+        echo "error: blank/missing --name <name>"
+        usage
+        exit 1
+    fi
 
-if [ "${VERSION:-}" = '' ]; then
-    echo "error: blank/missing --version <version>"
-    usage
-    exit 1
-fi
+    if [ "${VERSION:-}" = '' ]; then
+        echo "error: blank/missing --version <version>"
+        usage
+        exit 1
+    fi
 
-if [ "${RELEASE:-}" = '' ]; then
-    echo "error: blank/missing --release <release>"
-    usage
-    exit 1
-fi
+    if [ "${RELEASE:-}" = '' ]; then
+        echo "error: blank/missing --release <release>"
+        usage
+        exit 1
+    fi
 
-if [ "${ARCH:-}" = '' ]; then
-    echo "error: blank/missing --arch <architecture>"
-    usage
-    exit 1
-fi
+    if [ "${ARCH:-}" = '' ]; then
+        echo "error: blank/missing --arch <architecture>"
+        usage
+        exit 1
+    fi
 
-if [ "${MAINTAINER:-}" = '' ]; then
-    echo "error: blank/missing --maintainer <maintainer>"
-    usage
-    exit 1
-fi
+    if [ "${MAINTAINER:-}" = '' ]; then
+        echo "error: blank/missing --maintainer <maintainer>"
+        usage
+        exit 1
+    fi
 
-if [ "${SUMMARY:-}" = '' ]; then
-    echo "error: blank/missing --summary <summary>"
-    usage
-    exit 1
-fi
+    if [ "${SUMMARY:-}" = '' ]; then
+        echo "error: blank/missing --summary <summary>"
+        usage
+        exit 1
+    fi
 
-if [ "${DESCRIPTION:-}" = '' ]; then
-    echo "error: blank/missing --description <description>"
-    usage
-    exit 1
-fi
+    if [ "${DESCRIPTION:-}" = '' ]; then
+        echo "error: blank/missing --description <description>"
+        usage
+        exit 1
+    fi
 
-if [ "${LICENSE:-}" = '' ]; then
-    echo "error: blank/missing --license <license>"
-    usage
-    exit 1
-fi
+    if [ "${LICENSE:-}" = '' ]; then
+        echo "error: blank/missing --license <license>"
+        usage
+        exit 1
+    fi
 
-if [ "${CHANGELOG_PATH:-}" = '' ]; then
-    echo "error: blank/missing --changelog-file <path>"
-    usage
-    exit 1
-fi
+    if [ "${CHANGELOG_PATH:-}" = '' ]; then
+        echo "error: blank/missing --changelog-file <path>"
+        usage
+        exit 1
+    fi
+}
+
+validate
 
 cd /src
 
@@ -170,10 +175,10 @@ fi
 LIC="$LIC
 $LICENSE"
 printf "$LIC\n" >/tmp/LICENSE
-mkdir -p "$INTERNAL_DIR/$BANNER/data/usr/share/licenses/$NAME"
-cp /tmp/LICENSE "$INTERNAL_DIR/$BANNER/data/usr/share/licenses/$NAME/LICENSE"
+mkdir -p "$INTERNAL_DIR/$BANNER/$ROCKHOPPER_DATA_DIR/usr/share/licenses/$NAME"
+cp /tmp/LICENSE "$INTERNAL_DIR/$BANNER/$ROCKHOPPER_DATA_DIR/usr/share/licenses/$NAME/LICENSE"
 
-cp -r data "$INTERNAL_DIR/$BANNER"
+cp -r "$ROCKHOPPER_DATA_DIR" "$INTERNAL_DIR/$BANNER"
 cd "$INTERNAL_DIR"
 tar czf "$BANNER.tar.gz" "$BANNER"
 cd /src
@@ -216,7 +221,7 @@ mkdir -p \"%%{buildroot}/usr/share/licenses/$NAME\"
 cp /tmp/LICENSE \"%%{buildroot}/usr/share/licenses/$NAME/LICENSE\"
 "
 
-cd /src/data
+cd "/src/$ROCKHOPPER_DATA_DIR"
 for f in $(find . -print); do
     f="${f#./}"
 
@@ -227,9 +232,9 @@ for f in $(find . -print); do
     if [ -d "$f" ]; then
         SPEC="$SPEC\nmkdir -p \"%%{buildroot}/$f\""
     elif [ -f "$f" ]; then
-        SPEC="$SPEC\ncp "/src/data/$f" %%{buildroot}/$f"
+        SPEC="$SPEC\ncp \"/src/$ROCKHOPPER_DATA_DIR/$f\" \"%%{buildroot}/$f\""
     else
-        echo "error: unsupported file system file type for path: data/$f"
+        echo "error: unsupported file system file type for path: $ROCKHOPPER_DATA_DIR/$f"
         exit 1
     fi
 done
diff --git a/docker/slack/rockhopper b/docker/slack/rockhopper
--- a/docker/slack/rockhopper
+++ b/docker/slack/rockhopper
@@ -20,6 +20,7 @@ usage() {
     printf -- "--help\t\t\t\tShow usage menu.\n"
 }
 
+ROCKHOPPER_DATA_DIR='rockhopper-data'
 INTERNAL_DIR='/tmp/build'
 ARTIFACT_DIR='.rockhopper/slack'
 
@@ -99,53 +100,57 @@ while [ "$#" -ge 1 ]; do
     esac
 done
 
-if [ "${NAME:-}" = '' ]; then
-    echo "error: blank/missing --name <name>"
-    usage
-    exit 1
-fi
+validate() {
+    if [ "${NAME:-}" = '' ]; then
+        echo "error: blank/missing --name <name>"
+        usage
+        exit 1
+    fi
 
-if [ "${VERSION:-}" = '' ]; then
-    echo "error: blank/missing --version <version>"
-    usage
-    exit 1
-fi
+    if [ "${VERSION:-}" = '' ]; then
+        echo "error: blank/missing --version <version>"
+        usage
+        exit 1
+    fi
 
-if [ "${RELEASE:-}" = '' ]; then
-    echo "error: blank/missing --release <release>"
-    usage
-    exit 1
-fi
+    if [ "${RELEASE:-}" = '' ]; then
+        echo "error: blank/missing --release <release>"
+        usage
+        exit 1
+    fi
 
-if [ "${ARCH:-}" = '' ]; then
-    echo "error: blank/missing --arch <architecture>"
-    usage
-    exit 1
-fi
+    if [ "${ARCH:-}" = '' ]; then
+        echo "error: blank/missing --arch <architecture>"
+        usage
+        exit 1
+    fi
 
-if [ "${MAINTAINER:-}" = '' ]; then
-    echo "error: blank/missing --maintainer <maintainer>"
-    usage
-    exit 1
-fi
+    if [ "${MAINTAINER:-}" = '' ]; then
+        echo "error: blank/missing --maintainer <maintainer>"
+        usage
+        exit 1
+    fi
 
-if [ "${SUMMARY:-}" = '' ]; then
-    echo "error: blank/missing --summary <summary>"
-    usage
-    exit 1
-fi
+    if [ "${SUMMARY:-}" = '' ]; then
+        echo "error: blank/missing --summary <summary>"
+        usage
+        exit 1
+    fi
 
-if [ "${LICENSE:-}" = '' ]; then
-    echo "error: blank/missing --license <license>"
-    usage
-    exit 1
-fi
+    if [ "${LICENSE:-}" = '' ]; then
+        echo "error: blank/missing --license <license>"
+        usage
+        exit 1
+    fi
 
-if [ "${URL:-}" = '' ]; then
-    echo "error: blank/missing --url <homepage>"
-    usage
-    exit 1
-fi
+    if [ "${URL:-}" = '' ]; then
+        echo "error: blank/missing --url <homepage>"
+        usage
+        exit 1
+    fi
+}
+
+validate
 
 cd /src
 
@@ -180,7 +185,7 @@ fi
 LIC="$LIC
 $LICENSE"
 printf "$LIC\n" >"$INTERNAL_DIR/usr/doc/${NAME}-${VERSION}/LICENSE"
-cp -r data/* "$INTERNAL_DIR"
+cp -r "$ROCKHOPPER_DATA_DIR/"* "$INTERNAL_DIR"
 
 ARTIFACT="${NAME}-${VERSION}-${RELEASE}-${ARCH}-build.tgz"
 
