work around xbps-create validation bugs; account for void linux noarch deprecation; work around awscli quirks

diff --git a/docker/void-linux-musl/rocklet b/docker/void-linux-musl/rocklet
--- a/docker/void-linux-musl/rocklet
+++ b/docker/void-linux-musl/rocklet
@@ -14,9 +14,9 @@ ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
 ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
 ROCKHOPPER_DATA="${ROCKHOPPER_DATA:-"$ROCKHOPPER_MOUNT/rockhopper-data"}"
 ROCKHOPPER_SPECS="${ROCKHOPPER_SPECS:-"$HOME/rockhopper-specs"}"
-ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-"$ROCKHOPPER_MOUNT/.rockhopper/void-linux"}"
+ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-"$ROCKHOPPER_MOUNT/.rockhopper/void-linux-musl"}"
 ROCKHOPPER_XBPS_BUILD="${ROCKHOPPER_XBPS_BUILD:-/tmp/void-linux-musl}"
-ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-*}"
+ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-}"
 
 # Forward rockhopper environment variables to Jinja
 for K in $(compgen -v | grep '^ROCKHOPPER_'); do
@@ -89,6 +89,19 @@ validate() {
             exit 1
         fi
     done
+
+    case "$ROCKHOPPER_ARCH" in
+        '*')
+            echo "error: xbps-create malfunctions with arch '*'. select a specific architecture: https://docs.voidlinux.org/installation/index.html" >&2
+            exit 1
+            ;;
+        'noarch')
+            echo "error: void linux has deprecated 'noarch' packages. select a specific architecture: https://docs.voidlinux.org/installation/index.html" >&2
+            exit 1
+            ;;
+        *)
+            ;;
+    esac
 }
 
 clean() {
